version: '2'

services:
  cloud:
    image: cloudimage
    container_name: cloud_container
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    container_name: pg_jdbc
    image: postgres:16
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    ports:
      - "8081:5432"